### ISSUE TITLE
[mimir-distributed] [Epic] collect breaking changes for 3.0.0 of the chart

### ISSUE THREAD

**Issue by krajorama** [grafana/helm-charts#1309]
Targeting end of June or early August 2022

- [ ] Update minimum required Kubernetes version from 1.10. Possibly to 1.21 ? Needs investigation.
- [ ] Remove redundant non headless services (ref: #1307) Break: configuration
- [ ] Use non-root image (ref: #1282) Break: existing files on PVC need to be chown-ed . 
- [ ] Move activity log somewhere from /data, as it causes warning in Alertmanager `{"caller":"multitenant.go:1186","component":"MultiTenantAlertmanager","file":"/data/metrics-activity.log","level":"warn","msg":"ignoring unexpected file while scanning local alertmanager configs","ts":"2022-04-27T22:05:37.499007346Z"}` Break: configuration
- [x] Rename `memcached` service to `memcached-chunks` or something more specific, reflecting its intended usage. Break: configuration, possibly causing cache unavailable during upgrade. 
- [x] Remove dependency on bitnami memcached and introduce our own version like loki-distributed (#1315 ). Set up proper ServiceMonitor CRDs. Break: less values supported for memcached - not full bitnami anymore

**Comment by dimitarvdimitrov** [comment]
> Move activity log somewhere from /data, as it causes warning in Alertmanager

The problem comes from the fast that the activity log and the AM temporary directory are interfering, right? Changing the activity log is a breaking change, but we can change the `alertmanager.data_dir`. The `data_dir` directory does not need to be persisted during restarts ([doc](https://grafana.com/docs/enterprise-metrics/v2.0.x/config/reference/#alertmanager)), I think it's ok to change the value of it and not consider this a breaking change.

**Comment by krajorama** [comment]
> > Move activity log somewhere from /data, as it causes warning in Alertmanager
> 
> The problem comes from the fast that the activity log and the AM temporary directory are interfering, right? Changing the activity log is a breaking change, but we can change the `alertmanager.data_dir`. The `data_dir` directory does not need to be persisted during restarts ([doc](https://grafana.com/docs/enterprise-metrics/v2.0.x/config/reference/#alertmanager)), I think it's ok to change the value of it and not consider this a breaking change.

Quite possibly, but I haven't had time to test it out

**Comment by krajorama** [comment]
this is now tracker internally, closing. The items regarding memcached will be included in 3.0 release of the chart.

**Comment by dimitarvdimitrov** [comment]
> this is now tracked internally, closing. The items regarding memcached will be included in 3.0 release of the chart.

any reason for not tracking it publicly as well?
